### ISSUE TITLE
Create A Release

### ISSUE THREAD

**Issue by jw327** [jw327/dsci-310-group-01#16]
Just before you submit the milestone 1, create a release on your project repository on GitHub and name it 0.0.1 ([how to create a release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release)). This release allows us and you to easily jump to the state of your repository at the time of submission for grading puroposes, while you continue to work on your project for the next milestone.

**Comment by jw327** [comment]
@AniswagMC @longfei-g 
Please look over everything for the milestone and let me know if everything looks good so that I can create a release. Thanks!

**Comment by longfei-g** [comment]
I just made a commit to check, and everything look good to me!
